# Site settings
title: "Anne's cleaning services"
email: "annescleaning2022@gmail.com"
email_display: 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

# Phone numbers
whatsapp_en: 14703586805
whatsapp_es: 14703430811

whatsapp_en_display: "470 358 6805 (English)" 
whatsapp_es_display: "470 343 0811 (Spanish)"
